"""
report7.py
===========
The handoff report for a drop_motifs7 run.

Written for the same purpose the drop_motifs5 report served: every choice
the run made is stated so it can be graded and corrected, rather than
being buried in the figures.
"""

import json

from Pipelines.drop_motifs import passes7

HEADER = """# drop_motifs7 — multi-scale detection and the corrected figure set

Generated by `python Pipelines/drop_motifs/run_drop6_report.py`.

This run answers a review of `Plots/drop_motifs5/`. It does not replace
that run: `drop_motifs5` is left in place and every base-pass count here
reproduces it exactly, so the two are comparable span by span.

## What changed

### Detection is multi-scale

Four passes per span, merged with the base pass winning any collision:

| pass | what it is | why |
|---|---|---|
| `base` | the derived scale, exactly as drop_motifs5 ran it | unchanged, so every previously validated count still reproduces |
| `fine` | the detector at the best of a ladder of finer widths | the small events a single derived scale frames past |
| `sens` | the slope gate relaxed as far as window purity allows | spans whose events are gentle rather than sharp |
| `micro` | relaxed depth/dominance/rise gates, scanned segment |
| `inv` | the same detector on `-x` | events that go the other way — the operator's suggestion for ID 26, the supervisor's for ID 385 |

The `fine` rung is chosen by how many CLEAN events it finds that the base
pass did **not**, so a scale that merely re-finds what we already had
scores zero. The `sens` rung is the most sensitive gate whose windows stay
at least 90% clean, so sensitivity is never bought by reintroducing the
burst-window defect that purity exists to catch.

**How the micro pass was found.** ID 26 and ID 28 were both still badly
under-detecting after drop_motifs6 - 2 events against ~44 counted by eye,
and 19 against >90. Neither was a scale problem and neither was a detrend
problem. Instrumenting the detector's own rejection counters showed it was
FINDING the events and then discarding them: on ID 26 at segment 200 s, 67
candidates became 15 confirmed, with 21 rejected as shallow, 18 for having
too small a rise, and 12 as not dominant in their own window.

All three gates are relative to the biggest thing in view, which is right
for finding a span's dominant motif and wrong for finding everything
across scales. Relaxing all three and scanning the segment length gives:

| span | drop_motifs6 | drop_motifs7 | window purity |
|---|---:|---:|---:|
| ID 26 | 2 | 36+ | 0.95 |
| ID 28 | 19 | 79+ | 0.87 |
| ID 385 | 24 | 44+ | 0.91 |

`up_runs` - the count of rising runs in the encoded string, which needs no
gate to produce - is a useful independent check: it read 94 on ID 26 and
100 on ID 28, bracketing the operator's counts from above as it should.

### Figures carry six corrections

1. **Alignment.** Traces are aligned on the median of the flat run before
   the drop, not on the single sample at the onset index. The old rule
   shifted every trace by one sample's noise, which is why the ID 8 panel
   showed four different pre-drop heights under a caption promising one.
2. **One window length.** Every overlay set is cut to the smallest common
   extent about its onset, so traces no longer stop at different places
   for reasons unrelated to the motif.
3. **Scale and direction never share an axis.** Motifs are split into
   octave bands, and only where the spread warrants it; rises from the
   inverted pass are never drawn over drops.
4. **Outliers do not set the scale.** Flagged by a robust MAD score on
   drop depth, drawn de-emphasised, allowed to run off the axes. The
   limits come from the inliers, and the count is stated on the panel.

5. **One hue per family.** Each scale band gets its own colour and its own
   gradient through time - green, blue, purple, teal for drops, orange and
   pink for the inverted pass - and the window shading on the span plot
   uses the same hue, so a trace can be tied back to the stretch of signal
   it came from. Red, yellow, black and white are excluded; what used red
   (impure windows, outliers) is now distinguished by dash pattern.
6. **The height-to-width ratio is locked, not fitted.** Every panel in a
   figure shares one millivolt-per-second scale, derived from that
   figure's median event and stated on it. A motif twice as steep as its
   neighbour is drawn twice as steep, and panels become narrow or wide as
   their own data demands instead of every one being stretched to fill an
   identical box. This was what flattened ID 34's motifs into lines.

The dendrogram is now three ROWS - the tree with its branches running down,
the motifs beneath their own leaves, the family overlays beneath their own
branches - rather than three columns with the tree on its side.

An inverted pass that finds fewer than two motifs is discarded rather than
drawn: the pass exists to find a population going the other way, and one
lone rise costs a panel and a hue to say nothing.

### The library cannot collide with the previous one

Keys are `id{cat:03d}_r{rec}_{pass}_{onset}`. The pass tag means a
fine-pass motif at the same onset as a base-pass one is a distinct row
rather than a silent overwrite, and the key is a pure function of its
inputs, so re-running a pass is idempotent rather than duplicating.
"""


def write_report(summaries, out_dir):
    spans = [s for s in summaries if isinstance(s.get("catalogue_id"), int)]
    pooled = next((s.get("pooled") for s in summaries
                   if s.get("catalogue_id") == "ALL"), None)

    lines = [HEADER, "", "## Summary", ""]
    total = sum(s["n_motifs"] for s in spans)
    pure = sum(s["n_pure"] for s in spans)
    lines.append(f"**{total} motifs over {len(spans)} spans, {pure} pure.**")
    lines.append("")
    lines.append("| ID | span | n | pure | base | fine | sens | micro | inv | "
                 "bands | annot |")
    lines.append("|---:|---|---:|---:|---:|---:|---:|---:|---:|---|---:|")
    for s in spans:
        kept = s["per_pass_kept"]
        span = (f"{s['span_hours'][0]}-{s['span_hours'][1]} h"
                if s["span_hours"] else "whole recording")
        lines.append(
            f"| {s['catalogue_id']} | {span} | {s['n_motifs']} | {s['n_pure']} "
            f"| {kept.get('base', 0)} | {kept.get('fine', 0)} "
            f"| {kept.get('sens', 0)} | {kept.get('micro', 0)} "
            f"| {kept.get('inv', 0)} "
            f"| {len(s['scale_band_labels'])} "
            f"| {s['annotated_n'] if s['annotated_n'] is not None else '-'} |")

    lines += ["", "`annot` is the count the catalogue states in prose where "
                  "it states one. It is a CHECK and never an input: no "
                  "parameter is derived from it. Compare it against the "
                  "`base` column, which is the pass drop_motifs5 ran.", ""]

    if pooled:
        lines += ["## Pooled", "",
                  f"- {pooled.get('n_pure', 0)} pure motifs, "
                  f"{pooled.get('excluded', 0)} impure excluded",
                  "", "![pooled dendrogram](ALL_dendrogram.png)",
                  "![pooled rose](ALL_rose.png)", ""]

    lines += ["## Per span", ""]
    for s in spans:
        cid = s["catalogue_id"]
        lines += [f"### ID {cid}", "", f"> {s['note']}", ""]
        lines.append(f"- {s['n_motifs']} motifs, {s['n_pure']} pure, "
                     f"{s['n_duplicates_dropped']} cross-pass duplicates "
                     f"dropped from {s['n_before_dedup']} raw detections")
        lines.append(f"- scale bands: {', '.join(s['scale_band_labels'])}")
        for key in passes7.PASS_ORDER:
            info = s["passes"].get(key)
            if not info or not info.get("ran"):
                continue
            extra = []
            if info.get("divisor"):
                extra.append(f"width / {info['divisor']:g}")
            if info.get("slope_sigma"):
                extra.append(f"slope_sigma {info['slope_sigma']:g}")
            if info.get("segment_seconds"):
                extra.append(f"segment {info['segment_seconds']:.1f} s")
            lines.append(f"  - `{key}` ({passes7.PASS_LABELS[key]}): "
                         f"{info['n_events']} found"
                         + (f" — {', '.join(extra)}" if extra else "")
                         + f", {s['per_pass_kept'].get(key, 0)} kept")
        lines += ["",
                  f"![overlays](id{cid:03d}_overlays.png)",
                  f"![overlay](id{cid:03d}_overlay.png)",
                  f"![dendrogram](id{cid:03d}_dendrogram.png)",
                  f"![rose](id{cid:03d}_rose.png)", ""]

    path = out_dir / "REPORT.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    (out_dir / "run_summary.json").write_text(
        json.dumps(summaries, indent=2, default=float), encoding="utf-8")
    return str(path)
