"""
report5.py
===========
The handoff report: everything a reader with no context needs to grade the
auto-derived parameters, one span at a time, plus the pooled figures.

It is written to be pasted into a fresh conversation together with the
operator's own corrections, so it states a VERDICT per span rather than
only numbers. A reader given a table of parameters can only agree with it;
a reader given "this span passed, and here is why I think so" can disagree
in one word, and the disagreement is the signal worth feeding back.

ASCII only, deliberately. This file is edited by scripts as often as by
hand, and a degree sign that survives one round trip through the
platform's default encoding and not the next produces a source file that
no longer parses - which happened once already. "deg" costs nothing and
cannot break.
"""

from Working.Detection.drop_motifs.autoparams import (
    CONFIDENCE_GATE,
    DEDUP_INTERVAL_FRAC,
    DETREND_FEATURES,
    SEGMENTS_PER_FEATURE,
)

VERDICT_MARK = {"pass": "PASS", "suspect": "SUSPECT", "fail": "FAIL"}

POOLED_KEY = "ALL"


def _spans(summaries):
    """Only the real spans.

    The pooled entry rides in the same list so the caller has one thing to
    pass around, but it has no span, no verdict and no parameters, and
    every table below would otherwise need a special case for it.
    """
    return [s for s in summaries if s.get("catalogue_id") != POOLED_KEY]


def _pooled(summaries):
    return next((s["pooled"] for s in summaries
                 if s.get("catalogue_id") == POOLED_KEY), None)


def _hours(span):
    return "whole recording" if span is None else f"{span[0]}-{span[1]} h"


def _figure_name(path):
    return str(path).replace("\\", "/").split("/")[-1]


def write_report(summaries, out_dir):
    path = out_dir / "AUTODERIVE_REPORT.md"
    lines = []
    add = lines.append

    spans = _spans(summaries)
    n = len(spans)
    passed = sum(1 for s in spans if s["verdict"] == "pass")
    suspect = sum(1 for s in spans if s["verdict"] == "suspect")
    failed = sum(1 for s in spans if s["verdict"] == "fail")

    add("# Five-stage drop detection - auto-derived parameters, per span\n")
    add("Generated by `python Pipelines/drop_motifs/run_drop5_report.py`.\n")
    add("**What this is for.** Every parameter below was derived from the "
        "signal rather than hand-tuned, and this report exists so the "
        "derivation can be graded span by span. Each row carries my own "
        "verdict and the reason for it; correcting those verdicts is the "
        "feedback that will improve the derivation.\n")

    _how_derived(add)
    _how_to_read(add)

    add(f"## Summary - {passed} pass, {suspect} suspect, {failed} fail "
        f"of {n}\n")
    add("| ID | span | morph | expected | n | annot | purity | ACF conf | "
        "segment s | detrend s | verdict |")
    add("|---:|---|---|---|---:|---:|---:|---:|---:|---:|---|")
    for s in sorted(spans, key=lambda r: r["catalogue_id"]):
        params = s["params"]
        morph = s["morphology"]
        expected = s["expected_morphology"]
        add(
            f"| {s['catalogue_id']} | {_hours(s['span_hours'])} | {morph} | "
            f"{expected}{'' if morph == expected else ' **!**'} | "
            f"{s['n_events']} | "
            f"{s['annotated_n'] if s['annotated_n'] is not None else '-'} | "
            f"{s['purity_clean_fraction']:.2f} | {s['acf_confidence']:.2f} | "
            f"{params.get('segment_seconds', float('nan')):.1f} | "
            f"{params.get('detrend_window_s', float('nan')):.0f} | "
            f"{VERDICT_MARK[s['verdict']]} |")
    add("")
    add("`expected` is the morphology a reader of the catalogue's own "
        "`Elements` column would predict; **!** marks where the detector "
        "chose differently. That is a disagreement to adjudicate, not "
        "necessarily an error - the catalogue names the dominant shape of "
        "a span and the detector picks the one its windows are built "
        "from.\n")

    _pooled_section(add, _pooled(summaries))
    _library_section(add)

    add("## Per span\n")
    for s in sorted(spans, key=lambda r: r["catalogue_id"]):
        _span_block(add, s)

    _knobs(add)

    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _how_derived(add):
    add("## How the parameters are derived\n")
    add("Two parameters are time-scaled and everything else in the "
        "detector is dimensionless by construction (`slope_sigma` is a "
        "multiple of the noise, `min_depth_frac` a fraction of the deepest "
        "fall, the window multipliers fractions of the fall). Both derive "
        "from the span's **feature width** - the lag at which its "
        "autocorrelation falls to half height, which measures how wide one "
        "event is rather than how far apart events are:\n")
    add(f"- `segment_seconds = width / {SEGMENTS_PER_FEATURE:g}`")
    add(f"- `detrend_window_s = width x {DETREND_FEATURES:g}`")
    add(f"- `min_separation_s = {DEDUP_INTERVAL_FRAC:g} x the measured "
        f"event spacing`, applied once to the chosen pass\n")
    add("The width was chosen over the period by measurement against the "
        "six previously hand-tuned spans: `segment / width` spreads 4x "
        "across them and clusters at ~0.2, while `segment / period` "
        "spreads 51x. A period is the spacing *between* events; a segment "
        "has to resolve the *inside* of one. Mushroom_260720 is the case "
        "that forces the distinction - its icicles are ~50 s and spaced "
        "~1400 s apart, so a period-derived segment made the icicle "
        "smaller than one segment and the detector returned zero events on "
        "a recording with twenty-six of them.\n")
    add("The width is then **refined from the detections themselves** - "
        "the median event extent of what came back - because a "
        "frequency-modulated span has no single stationary scale for any "
        "estimator to find. Three candidate scales are tried first (the "
        "lobe width and two fractions of the period), the best is refined, "
        "and the best is the one finding the most events among passes "
        "whose events do not overlap each other.\n")
    add("**Annotated counts are a check, never an input.** No parameter is "
        "derived from them, so a span matching its annotated count is "
        "evidence rather than arithmetic.\n")


def _how_to_read(add):
    add("## How to read the verdict\n")
    add("The headline metric is **window purity**: the detector's own "
        "slope gate is re-run *inside* each stored window and the "
        "qualifying falls are counted. A correctly extracted window holds "
        "exactly 1. The defect this work addresses scored 3.\n")
    add("| verdict | meaning |")
    add("|---|---|")
    add("| PASS | >=90% of windows hold exactly one fall, and any "
        "annotated count matches |")
    add("| SUSPECT | 60-90% clean, or the count disagrees with a human |")
    add("| FAIL | <60% clean, or nothing found |\n")
    add(f"An autocorrelation confidence below {CONFIDENCE_GATE:g} is noted "
        "on the row: it means the scale came from refinement rather than "
        "from the seed, which is not itself a problem but is worth knowing "
        "when judging why a span behaved as it did.\n")


def _pooled_section(add, pooled):
    if not pooled:
        return
    add("## Pooled across every span\n")
    add(f"One tree and one rose over all **{pooled['n_pure']} pure "
        f"motifs** from every span, with {pooled['excluded']} impure "
        f"windows excluded before anything was computed.\n")

    info = pooled.get("dendrogram_info") or {}
    if info.get("n_clusters"):
        add(f"- dendrogram: k={info['n_clusters']}, cophenetic "
            f"r={info['cophenetic_r']:.2f}. Leaves are coloured by "
            f"catalogue ID, so a branch mixing colours is a shape family "
            f"shared ACROSS recordings - which is the cross-scale claim "
            f"the whole exercise is for. Above 70 leaves the per-leaf "
            f"labels are replaced by that colour strip, because a legible "
            f"font at 362 leaves produced a 9,398-pixel-tall image.")
        add(f"- cluster composition by span: `{info.get('composition', {})}`")
    elif info.get("reason"):
        add(f"- dendrogram: not drawn - {info['reason']}")

    rose = pooled.get("rose_info") or {}
    if rose.get("n"):
        add(f"- rose: mean {rose['mean_deg']:.1f} deg, "
            f"R={rose['resultant_length']:.3f}, circular SD "
            f"{rose['circular_sd_deg']:.1f} deg, uniformity "
            f"p={rose['uniformity_p']:.2g}")
    add("")

    for key in ("dendrogram", "rose"):
        if pooled.get(key):
            add(f"![pooled {key}]({_figure_name(pooled[key])})")
    add("")


def _library_section(add):
    add("## The motif library\n")
    add("Every extracted window is persisted under `motifs/` as "
        "`motifs.csv` (the index), `motifs.npz` (the arrays) and "
        "`manifest.json`. Each row carries `purity` and `is_pure`, so a "
        "consumer can take the clean subset without re-running detection, "
        "and `raw_mv` / `detrended_mv` / `t_s` are stored per motif. Keys "
        "lead with the catalogue ID because two spans here are sub-spans "
        "of two others on the same recording (ID 20 inside ID 1, ID 21 "
        "inside ID 3), and a recording-and-onset key would collide between "
        "them.\n")
    add("The format is the one `cluster.py` and `gradients.py` already "
        "read, which is why every figure above is drawn from the library "
        "rather than from the detection run that produced it - a figure "
        "drawn from one and a library written from the other is the class "
        "of mistake that produces a plot nobody can reproduce.\n")


def _span_block(add, s):
    cid = s["catalogue_id"]
    add(f"### ID {cid} - {VERDICT_MARK[s['verdict']]}\n")
    add(f"> {s['note']}\n")
    add(f"- **verdict reason**: {s['verdict_reason']}")
    add(f"- annotation `{s['annotation_id']}`, recording "
        f"`{s['recording_id']}`, {_hours(s['span_hours'])}, "
        f"{s['n_samples']} samples @ {s['fs']:g} Hz")
    add(f"- morphology chosen **{s['morphology']}** "
        f"(catalogue suggests {s['expected_morphology']})")
    add(f"- events **{s['n_events']}**"
        + (f", annotated {s['annotated_n']}"
           if s["annotated_n"] is not None else ", no annotated count"))
    add(f"- window purity **{s['purity_clean_fraction']:.2f}** clean; "
        f"histogram (falls per window) `{s['purity_histogram']}`")
    add(f"- median window {s['median_window_s']:.0f} s = "
        f"{s['window_over_interval']:.2f}x the measured event spacing")
    if s.get("diagnosis"):
        add(f"- **diagnosis**: {s['diagnosis']}")

    add(f"- scale: ACF period {s['acf_period_s']:.0f} s at confidence "
        f"{s['acf_confidence']:.2f}; ACF lobe width "
        f"{s['acf_width_s']:.0f} s; refined width "
        f"**{s['refined_width_s']:.0f} s**; refined median interval "
        f"{s['refined_interval_s']:.0f} s; "
        f"{'converged' if s['converged'] else 'did NOT converge'}")

    params = s["params"]
    add(f"- derived: `segment_seconds="
        f"{params.get('segment_seconds', float('nan')):.2f}`, "
        f"`detrend_window_s="
        f"{params.get('detrend_window_s', float('nan')):.0f}`, "
        f"`min_separation_s="
        f"{params.get('min_separation_s', float('nan')):.0f}`")

    counts = s["counts"]
    if counts:
        live = {k: v for k, v in counts.items() if v}
        add(f"- detector counts: `{live}`")

    diagnostics = s["diagnostics"]
    if diagnostics.get("stage_histogram"):
        add(f"- five-stage histogram (d D S U u): "
            f"`{diagnostics['stage_histogram']}`")
        add(f"- slope threshold "
            f"{diagnostics.get('slope_threshold_mv_per_s', float('nan')):.3f}"
            f" mV/s, from a noise sigma of "
            f"{diagnostics.get('sigma_slope_mv_per_s', float('nan')):.3f}")

    if s["events"]:
        depths = [e["drop_depth_mv"] for e in s["events"]]
        falls = [e["fall_duration_s"] for e in s["events"]]
        add(f"- depths {min(depths):.1f}-{max(depths):.1f} mV; "
            f"falls {min(falls):.0f}-{max(falls):.0f} s")

    figure_set = s.get("figure_set") or {}
    info = figure_set.get("dendrogram_info") or {}
    if info.get("n_clusters"):
        add(f"- dendrogram: k={info['n_clusters']}, cophenetic "
            f"r={info['cophenetic_r']:.2f} over {info['n']} pure motifs"
            + (f" ({info['excluded']} excluded)"
               if info.get("excluded") else ""))
    elif info.get("reason"):
        add(f"- dendrogram: not drawn - {info['reason']}")

    rose = figure_set.get("rose_info") or {}
    if rose.get("n"):
        add(f"- rose: mean {rose['mean_deg']:.1f} deg, "
            f"R={rose['resultant_length']:.3f}, circular SD "
            f"{rose['circular_sd_deg']:.1f} deg, uniformity "
            f"p={rose['uniformity_p']:.2g}")

    add("")
    add("| pass | phase | width in | segment | detrend | events | "
        "measured width | measured interval | ok | used |")
    add("|---:|---|---:|---:|---:|---:|---:|---:|:-:|:-:|")
    for t in s["trace"]:
        add(f"| {t['pass_index']} | {t['phase']} | "
            f"{t['feature_width_s']:.0f} | {t['segment_seconds']:.1f} | "
            f"{t['detrend_window_s']:.0f} | {t['n_events']} | "
            f"{t['measured_width_s']:.0f} | {t['measured_interval_s']:.0f} | "
            f"{'y' if t['admissible'] else 'n'} | "
            f"{'*' if t.get('selected') else ''} |")
    add("")

    figures = list(s.get("figures", []))
    for key in ("overlays", "dendrogram", "rose"):
        if figure_set.get(key):
            figures.append(figure_set[key])
    for figure in figures:
        add(f"![ID {cid}]({_figure_name(figure)})")
    add("")


def _knobs(add):
    add("## What to change if a span is wrong\n")
    add("| symptom | knob | where |")
    add("|---|---|---|")
    add("| segments too coarse; events missed whole | "
        "`SEGMENTS_PER_FEATURE` | "
        "`Working/Detection/drop_motifs/autoparams.py` |")
    add("| the detrend ate the event (amplitudes far too small) | "
        "`DETREND_FEATURES` | same |")
    add("| one event reported as several | `DEDUP_INTERVAL_FRAC`, or a "
        "coarser segment | same |")
    add("| windows hold a neighbour | `window_cap_mult`, "
        "`window_pad_frac`, `TIGHTEN_STEPS` | `detect5.py` |")
    add("| junk events with no real rise | `min_rise_frac` | "
        "`Detect5Params` |")
    add("| events where something bigger is in frame | "
        "`min_fall_dominance` | `Detect5Params` |")
    add("| wrong morphology chosen | `morphology='sharkfin'` or "
        "`'trough'` | `Detect5Params`, per span |")
    add("| too few / too many falls pass the gate | `slope_sigma` | "
        "`Detect5Params` |")
    add("| onset lands before the real drop | `trough_knee_frac` | "
        "`refine_onset` in `detect5.py` |")
    add("")
    add("Every one of these can be set per span without touching the "
        "derivation, by passing it through `autotune(..., **overrides)`.\n")
